# SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
# SPDX-License-Identifier: Apache-2.0
deployTarget: LOCAL

pachd:
  image:
    tag: local
  resources:
    requests:
      cpu: 250m
      memory: 512M
  service:
    type: NodePort
  metrics:
    enabled: false
  clusterDeploymentID: dev
  activateEnterprise: true
  registerWithEnterpriseServer: true
  enterpriseLicenseKey: ""
  enterpriseServerAddress: "grpc://pach-enterprise.enterprise.svc.cluster.local:1650"
  enterpriseCallbackAddress: "grpc://pachd.default.svc.cluster.local:1650"
  enterpriseRootToken: "valid-enterprise-token"
  mockIDP: true
  oauthClientID: "pachd"
  oauthIssuer: "http://pach-enterprise.enterprise.svc.cluster.local:1658/"
  oauthRedirectURI: "http://localhost:30657/authorization-code/callback"

console:
  enabled: true
  config:
    issuerURI: "http://pach-enterprise.enterprise.svc.cluster.local:1658/"
    oauthRedirectURI: "http://localhost:4000/oauth/callback/?inline=true"
    reactAppRuntimeIssuerURI: "http://localhost:31658/"
    oauthClientID: "dash"
    oauthClientSecret: "notsecret"
    graphqlPort: 4000
    oauthPachdClientID: "pachd"
    pachdAddress: "pachd-peer:30653"

etcd:
  service:
    type: NodePort

postgresql:
  service:
    type: NodePort
