deployTarget: LOCAL

oidc:
  mockIDP: true
  issuerURI: "http://pach-enterprise.enterprise.svc.cluster.local:1658/"

console:
  enabled: false
enterpriseServer:
  enabled: true
  service:
    type: NodePort
  image:
    tag: local
pachd:
  enabled: false
