# SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
# SPDX-License-Identifier: Apache-2.0
deployTarget: custom

oidc:
  issuerURI: "http://pach-enterprise.enterprise.svc.cluster.local:1658/"

pachd:
  image:
    tag: local
  resources:
    requests:
      cpu: 250m
      memory: 512M
  service:
    type: NodePort
  metrics:
    enabled: false
  clusterDeploymentID: dev
  # to enable enterprise features pass in pachd.activateEnterprise=true, and a valid pachd.enterpriseLicenseKey
  # enterpriseLicenseKey: ""
  activateEnterpriseMember: true
  enterpriseServerAddress: "grpc://pach-enterprise.enterprise.svc.cluster.local:1650"
  enterpriseCallbackAddress: "grpc://pachd.default.svc.cluster.local:1650"
  enterpriseRootToken: "valid-enterprise-token"
  storage:
    backend: MINIO
    minio:
      bucket: "pachyderm-test"
      endpoint: "minio.default.svc.cluster.local:9000"
      id: "minioadmin"
      secret: "minioadmin"
      secure: "false"
      signature: ""

etcd:
  service:
    type: NodePort

postgresql:
  service:
    type: NodePort
