# SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
# SPDX-License-Identifier: Apache-2.0
deployTarget: LOCAL

pachd:
  metrics:
    enabled: false
  clusterDeploymentID: dev
  activateEnterprise: true
  enterpriseLicenseKey: ""
  enterpriseServerAddress: "grpc://pach-enterprise.enterprise.svc.cluster.local:1650"
  enterpriseCallbackAddress: "grpc://pachd.default.svc.cluster.local:1650"
  enterpriseRootToken: "valid-enterprise-token"
  mockIDP: true
  oauthClientID: "pachd"
  oauthIssuer: "http://pach-enterprise.enterprise.svc.cluster.local:1658/"
  oauthRedirectURI: "http://localhost:30657/authorization-code/callback"

console:
  enabled: true
  config:
    issuerURI: "http://<ENTERPRISE-SERVER-IP>:1658/"
    oauthRedirectURI: "http://<CONSOLE-IP>:4000/oauth/callback/?inline=true"
    reactAppRuntimeIssuerURI: "http://<ENTERPRISE-SERVER-IP>:31658/"
    oauthClientID: "dash"
    oauthClientSecret: "<CONSOLE-CLIENT-SECRET>"
    graphqlPort: 4000
    oauthPachdClientID: "pachd"
    pachdAddress: "pachd-peer:30653"

enterpriseServer:
  enabled: false
