# SPDX-FileCopyrightText: Pachyderm, Inc. <info@pachyderm.com>
# SPDX-License-Identifier: Apache-2.0

deployTarget: LOCAL

pachd:
  activateEnterprise: false
  enterpriseLicenseKey: ""
  userAccessibleOauthIssuerHost: "localhost:30658"
  mockIDP: true
